version: '3.9'

services:
  amiloz_db:
    container_name: amiloz_db
    image: postgres:16-alpine
    ports:
      - "8089:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U randy -d amiloz_db" ]
      interval: 2s
      timeout: 10s
      retries: 5
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=HolaAmigo12+
      - POSTGRES_USER=randy
      - POSTGRES_DB=amiloz_db

  amiloz_server:
    depends_on:
      amiloz_db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"